### ISSUE TITLE
Fav counter is covered by the share button on Android

### ISSUE THREAD

**Issue by JakubValtar** [merveilles/The-Town#15]
![](https://s3-eu-central-1.amazonaws.com/merveilles/media_attachments/files/000/005/794/original/7c9cb925a8f3272d.png)

**Comment by neauoire** [comment]
I cannot replicate, someone else will have to make a fix for this.

**Comment by JakubValtar** [comment]
I will try to remote debug it from Chrome.

**Comment by JakubValtar** [comment]
![](https://s3-eu-central-1.amazonaws.com/merveilles/media_attachments/files/000/005/924/original/47f447775a753341.png)
