### ISSUE TITLE
Tiny green dot next to "liked" triangle

### ISSUE THREAD

**Issue by SomniusTiger** [merveilles/The-Town#32]
<img width="343" alt="screenshot 2018-12-25 02 46 11" src="https://user-images.githubusercontent.com/3317766/50416566-5bc92d80-07ef-11e9-9682-c2eac0617947.png">

This can be fixed by adjusting that background-image to have 
```css
background-repeat: no-repeat;
```

**Comment by neauoire** [comment]
<img width="395" alt="screen shot 2018-12-26 at 7 42 45 am" src="https://user-images.githubusercontent.com/1455726/50426080-dbcfc000-08e1-11e9-8dbf-5a7d11302f6a.png">

Fixed
