### ISSUE TITLE
Unable to interact with toots on the instance from sunbeam.city

### ISSUE THREAD

**Issue by jerebenitez** [merveilles/The-Town#42]
This first screen is what appear whenever I try to interact with a toot from the instance. It always appears when trying to interact with a post that I'm not viewing through sunbeam.city (in this case I opened [this](https://merveilles.town/@neauoire/101388676479951867) thread and clicked the icon to post a reply on the shown toot, but it appears when I do the same on any toot on any instance).
![interact_screen](https://user-images.githubusercontent.com/6274052/50939073-0da46300-145a-11e9-8fe7-866eecb23050.png)
Then the browser hung for a while (less than a minute probably, didn't time it) and then it showed me this msg:
![interact_response](https://user-images.githubusercontent.com/6274052/50939072-0d0bcc80-145a-11e9-9480-5249a3cce841.png)

Having to interact with toots this way happens all the time to me (maybe it's something having to do with my account), but the other instances redirect me to the same toot I tried to interact with except that I'm able to do so after authenticating. I only see this msg with merveilles, and it appears every time I follow these steps.

PS: sorry for not using thumbnails, I don't know how to do so yet.

**Comment by SomniusTiger** [comment]
Further updates: when trying to interact with a toot on snouts.online using my sunbeam.city account, I am encountering the same error. I'm not encountering the same error otherwise.

It seems like there may be something wrong with how sunbeam.city is federating with other instances! Are you able to replicate this as well, @jerebenitez? :o

**Comment by jerebenitez** [comment]
Sorry for the delay, I just woke up 😅 

When I tried to interact with a toot on snouts.online it gave me a 504 error, but navigating around was pretty slow to begin with, so it could be a server thing. I'm gonna try again later and let you know if the same happens to me. In that case I'll also notify sunbeam.city admin.

Thanks for your time!

**Comment by neauoire** [comment]
Should I close this as it's possibly not related to Merveilles itself?

**Comment by SomniusTiger** [comment]
Yup, this should be good to close! Lemme go ahead and do that, actually.

**Comment by jerebenitez** [comment]
I'll close it. Sorry for bothering you people with this. I've already sent a DM to cocoron so they can take a look at it.

Thanks for the help!

**Comment by neauoire** [comment]
I wouldn't bother cocoron about this actually, 
I think they've had quite enough of us already.
